services:
  hairdobooking_frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: hairdobooking_frontend
    container_name: hairdobooking_frontend
    ports:
      - "${APP_PORT:-3084}:3000"
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - WATCHPACK_POLLING_INTERVAL=1000
      - LARAVEL_INTERNAL_URL=http://hairdobooking
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:80
    volumes:
      - .:/usr/src/app
      - hairdobooking_frontend_node_modules:/usr/src/app/node_modules
    networks:
      - app-network
      - shared-network
    restart: unless-stopped
    stdin_open: true
    tty: true
networks:
  app-network:
    driver: bridge
  shared-network:
    external: true

volumes:
  hairdobooking_frontend_node_modules:
